services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - .data:/home/dynamodblocal/data
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx1g -Xms1g
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    networks:
      - sam-local-network

networks:
  sam-local-network:
    driver: bridge
