AWSTemplateFormatVersion: 2010-09-09
Description: >-
  backend

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ##### API Resources #####

  getUsers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/users/getUsers.default
      Description: A function to grab users' information
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "cognito-idp:AdminGetUser"
            Resource: !GetAtt CognitoUserPool.Arn
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:Query"
            Resource:
              - !GetAtt TeamMembersTable.Arn
              - !Sub "${TeamMembersTable.Arn}/index/EventIdIndex"
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:Scan"
            Resource: !GetAtt UsersTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /users
            Method: GET
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          COGNITO_USER_POOL_NAME: !Ref CognitoUserPool
          USERS_TABLE_NAME: !Ref UsersTable
          TEAM_MEMBERS_TABLE_NAME: !Ref TeamMembersTable

  insertUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/users/insertUser.default
      Description: A function to insert a user row for searching
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:PutItem"
            Resource: !GetAtt UsersTable.Arn
      Events:
        CognitoTrigger:
          Type: Cognito
          Properties:
            UserPool: !Ref CognitoUserPool
            Trigger: PostConfirmation
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable

  updateUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/users/updateUser.default
      Description: Updates the users' information in db
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:UpdateItem"
            Resource: !GetAtt UsersTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /users
            Method: PATCH
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable

  deleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/users/deleteUser.default
      Description: Deletes the users' information in db
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:DeleteItem"
            Resource: !GetAtt UsersTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /users
            Method: DELETE
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable

  getTeams:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/teams/getTeams.default
      Description: A function to get teams' information
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:BatchGetItem"
            Resource: !GetAtt TeamsTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /teams
            Method: GET
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          TEAMS_TABLE_NAME: !Ref TeamsTable

  updateTeams:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/teams/updateTeams.default
      Description: A function to update a team's information
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:BatchGetItem"
            Resource: !GetAtt TeamsTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /teams
            Method: PATCH
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          TEAMS_TABLE_NAME: !Ref TeamsTable

  getEvents:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/events/getEvents.default
      Description: A function to grab events
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:Scan"
            Resource: !GetAtt EventsTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /events
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          EVENTS_TABLE_NAME: !Ref EventsTable

  getEntries:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/events/getEntries.default
      Description: A function to grab event entries
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:Query"
            Resource:
              - !GetAtt EntriesTable.Arn
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:BatchGetItem"
            Resource:
              - !GetAtt TeamsTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /events/entries
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          ENTRIES_TABLE_NAME: !Ref EntriesTable
          TEAMS_TABLE_NAME: !Ref TeamsTable

  getEventInformation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/events/getEventInformation.default
      Description: A function to grab event information
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
            Resource:
              - !GetAtt EventsTable.Arn
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:Query"
            Resource:
              - !GetAtt EntriesTable.Arn
              - !GetAtt TeamMembersTable.Arn
              - !Sub "${TeamMembersTable.Arn}/index/EventIdIndex"
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /events/information
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          ENTRIES_TABLE_NAME: !Ref EntriesTable
          EVENTS_TABLE_NAME: !Ref EventsTable
          TEAM_MEMBERS_TABLE_NAME: !Ref TeamMembersTable

  registerVolunteer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/events/registerVolunteer.default
      Description: A function to register a member as a volunteer
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:Query"
            Resource:
              - !GetAtt TeamMembersTable.Arn
              - !Sub "${TeamMembersTable.Arn}/index/UserIdIndex"
              - !GetAtt EntriesTable.Arn
              - !Sub "${EntriesTable.Arn}/index/VolunteerIndex"
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:PutItem"
            Resource:
              - !GetAtt TeamMembersTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /events/volunteer
            Method: POST
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          ENTRIES_TABLE_NAME: !Ref EntriesTable
          TEAM_MEMBERS_TABLE_NAME: !Ref TeamMembersTable

  registerTeam:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/events/registerTeam.default
      Description: A function to register a team for an event
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:TransactWriteItems"
              - "dynamodb:PutItem"
            Resource:
              - !GetAtt EntriesTable.Arn
              - !GetAtt TeamsTable.Arn
              - !GetAtt TeamMembersTable.Arn
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:Query"
            Resource:
              - !GetAtt EventsTable.Arn
              - !GetAtt TeamMembersTable.Arn
              - !Sub "${TeamMembersTable.Arn}/index/EventIdIndex"
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /events/register
            Method: POST
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          ENTRIES_TABLE_NAME: !Ref EntriesTable
          TEAM_MEMBERS_TABLE_NAME: !Ref TeamMembersTable
          TEAMS_TABLE_NAME: !Ref TeamsTable
          EVENTS_TABLE_NAME: !Ref EventsTable

  paymentIntent:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/teams/updateTeams.default
      Description: A function to update a team's information
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /teams/paymentIntent
            Method: POST
            ApiId: !Ref HttpApiGateway

  paymentSucceeded:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/teams/updateTeams.default
      Description: A function to update a team's information
      Policies:
        - Statement:
            Effect: "Allow"
            Action:
              - "dynamodb:UpdateItem"
            Resource: !GetAtt EntriesTable.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /teams/paymentSucceeded
            Method: POST
            ApiId: !Ref HttpApiGateway
      Environment:
        Variables:
          ENTRIES_TABLE_NAME: !Ref EntriesTable

  ##### API Resources #####

  ##### DB Resources #####

  ### View README.md for the table data layouts ###

  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: teams
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  TeamMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: teamMembers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: EventIdIndex
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: events
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH

  EntriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: entries
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: volunteer
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
        - AttributeName: teamId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TeamIdIndex
          KeySchema:
            - AttributeName: teamId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: VolunteerIndex
          KeySchema:
            - AttributeName: volunteer
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ##### DB Resources #####

  ##### Cognito User Pool #####

  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: yorkshire-3-peaks-user-pool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email
      UsernameConfiguration:
        CaseSensitive: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      EmailConfiguration:
        SourceArn: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/yorkshirepeaks@gmail.com
        # manually verified the email via AWS console so we don't have the ARN reference
        # TODO - create a business email so that it is authed by DKIM so less risk of going into the spam folder - NEO mail
        ReplyToEmailAddress: yorkshirepeaks@gmail.com
        EmailSendingAccount: DEVELOPER
        From: The Yorkshire 3 Peaks Team <yorkshirepeaks@gmail.com>
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: |
          Hello,

          Your Yorkshire Three Peaks verification code is:

          {####}

          Enter this code in the app or website to continue.

          If you did not request this code, you can safely ignore this message.

          Thank you,

          The Yorkshire Three Peaks Team
        EmailSubject: Yorkshire 3 Peaks - Your Verification Code
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      MfaConfiguration: "OFF"
      DeletionProtection: ACTIVE
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: phone_number
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: true
          StringAttributeConstraints:
            MinLength: "0"
            MaxLength: "2048"
        - Name: "ice_number"
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: "0"
            MaxLength: "2048"
        - Name: "notify"
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: "0"
            MaxLength: "2048"
        - Name: email
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: true
          StringAttributeConstraints:
            MinLength: "0"
            MaxLength: "2048"
        - Name: given_name
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: true
          StringAttributeConstraints:
            MinLength: "0"
            MaxLength: "2048"
        - Name: family_name
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: true
          StringAttributeConstraints:
            MinLength: "0"
            MaxLength: "2048"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: yorkshire-3-peaks-user-pool-app-client
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      ReadAttributes:
        - custom:ice_number
        - custom:notify
        - email
        - phone_number
        - given_name
        - family_name
        - email_verified
      UserPoolId: !Ref CognitoUserPool
      WriteAttributes:
        - custom:ice_number
        - custom:notify
        - email
        - phone_number
        - given_name
        - family_name

  UserPoolGroupORGANISER:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: Organiser
      Precedence: 20
      Description: A group of volunteers that want to help organiser the future events

  UserPoolGroupADMIN:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: Admin
      Precedence: 10
      Description: A group people trained to look after the data in the db

  ##### Cognito User Pool #####

  ##### API Gateway #####

  # 2 Certs request manually:
  # - one in us-east-1 for the amplify application - 4f068f57-af87-4721-b205-df7275fbbe25
  # - one in eu-west-2 for the http-api - aec5a927-bae6-45a0-9ccf-ae918431df25

  # 1 CNAME DNS recorded added to api.yorkshirepeaks.co.uk to api gateway

  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Domain:
        DomainName: api.yorkshirepeaks.co.uk
        CertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/aec5a927-bae6-45a0-9ccf-ae918431df25
        EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          OAuth2Authorizer:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
              audience:
                - !Ref UserPoolClient
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: OAuth2Authorizer
      CorsConfiguration:
        AllowHeaders:
          - Authorization
          - Content-Type
          - Access-Control-Allow-Methods
          - Access-Control-Allow-Origin
          - Access-Control-Allow-Headers
          - Accept
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Requested-With
        AllowOrigins:
          - http://localhost:3000
          - https://yorkshirepeaks.co.uk
          - https://www.yorkshirepeaks.co.uk
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - DELETE
          - POST
          - PATCH

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod"
    Value: "https://api.yorkshirepeaks.co.uk/"
##### API Gateway #####
