name: Y3P CI/CD test pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  format-and-validate-checks:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Format check
        run: npm run format:check
      - name: Lint check
        run: npm run lint

  test-ui:
    runs-on: self-hosted
    # needs:
    #   - format-and-validate-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Runs cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          working-directory: ui
          wait-on: "http://localhost:3000"

  test-backend:
    runs-on: self-hosted
    needs:
      - format-and-validate-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install backend dependencies
        run: npm ci
        working-directory: "backend"
      - name: Backend tests
        run: npm run test
        working-directory: "backend"
